#!/usr/bin/env python3
"""Build the GitLab API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {
    'Broadcast Messages': 'Broadcast Msg',
    'Application Single': 'App Single',
    'Application': 'App Settings',
    'Applications': 'Apps',
    'REST API': 'REST API',
}

LINES = [
    {
        "name": 'Core APIs',
        "color": '#FC6D26',
        "stations": [
        ('REST API', (270, 195)),
        ('GraphQL', (430, 175)),
        ('OAuth2', (590, 165)),
        ('Webhooks', (760, 175)),
        ('Metadata', (940, 200)),
        ],
    },
    {
        "name": 'Repos & Code',
        "color": '#0E9D6E',
        "stations": [
        ('Projects', (270, 310)),
        ('Repositories', (440, 285)),
        ('Commits', (610, 285)),
        ('Branches', (780, 285)),
        ('Tags', (940, 310)),
        ],
    },
    {
        "name": 'CI/CD & Workflows',
        "color": '#E68B1F',
        "stations": [
        ('Pipelines', (270, 425)),
        ('Jobs', (440, 405)),
        ('Runners', (610, 405)),
        ('Issues', (770, 405)),
        ('Merge Requests', (940, 425)),
        ],
    },
    {
        "name": 'Deploy & Releases',
        "color": '#1E5BD0',
        "stations": [
        ('Releases', (270, 540)),
        ('Environments', (450, 515)),
        ('Deployments', (640, 515)),
        ('Bulk Imports', (820, 515)),
        ],
    },
    {
        "name": 'Identity & Admin',
        "color": '#7B3FE4',
        "stations": [
        ('Users', (270, 660)),
        ('Groups', (450, 635)),
        ('Admin', (610, 635)),
        ('Application', (770, 635)),
        ('Applications', (940, 660)),
        ],
    },
    {
        "name": 'Misc',
        "color": '#5A6275',
        "closed": True,
        "stations": [
        ('Avatar', (550, 770)),
        ('Broadcast Messages', (700, 770)),
        ('Version', (550, 815)),
        ('Application Single', (700, 815)),
        ],
    },
]

URL_OVERRIDES = {
    'REST API': 'https://apis.apis.io/apis/gitlab/gitlab-rest-api/',
    'GraphQL': 'https://apis.apis.io/apis/gitlab/gitlab-graphql-api/',
    'OAuth2': 'https://apis.apis.io/apis/gitlab/gitlab-oauth2-api/',
    'Webhooks': 'https://apis.apis.io/apis/gitlab/gitlab-webhooks/',
    'Metadata': 'https://apis.apis.io/apis/gitlab/apiv4metadata/',
    'Projects': 'https://apis.apis.io/apis/gitlab/apiv4projects/',
    'Repositories': 'https://apis.apis.io/apis/gitlab/apiv4repositories/',
    'Commits': 'https://apis.apis.io/apis/gitlab/apiv4commits/',
    'Branches': 'https://apis.apis.io/apis/gitlab/apiv4branches/',
    'Tags': 'https://apis.apis.io/apis/gitlab/apiv4tags/',
    'Pipelines': 'https://apis.apis.io/apis/gitlab/apiv4pipelines/',
    'Jobs': 'https://apis.apis.io/apis/gitlab/apiv4jobs/',
    'Runners': 'https://apis.apis.io/apis/gitlab/apiv4runners/',
    'Issues': 'https://apis.apis.io/apis/gitlab/apiv4issues/',
    'Merge Requests': 'https://apis.apis.io/apis/gitlab/apiv4merge-requests/',
    'Releases': 'https://apis.apis.io/apis/gitlab/apiv4releases/',
    'Environments': 'https://apis.apis.io/apis/gitlab/apiv4environments/',
    'Deployments': 'https://apis.apis.io/apis/gitlab/apiv4deployments/',
    'Bulk Imports': 'https://apis.apis.io/apis/gitlab/apiv4bulk-imports/',
    'Users': 'https://apis.apis.io/apis/gitlab/apiv4users/',
    'Groups': 'https://apis.apis.io/apis/gitlab/apiv4groups/',
    'Admin': 'https://apis.apis.io/apis/gitlab/apiv4admin/',
    'Applications': 'https://apis.apis.io/apis/gitlab/apiv4applications/',
    'Application': 'https://apis.apis.io/apis/gitlab/apiv4application/',
    'Application Single': 'https://apis.apis.io/apis/gitlab/apiv4application/',
    'Avatar': 'https://apis.apis.io/apis/gitlab/apiv4avatar/',
    'Broadcast Messages': 'https://apis.apis.io/apis/gitlab/apiv4broadcast-messages/',
    'Version': 'https://apis.apis.io/apis/gitlab/apiv4version/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The GitLab API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: gitlab/openapi · github.com/api-evangelist/gitlab',
        out_dir=Path(__file__).resolve().parent,
        out_basename='gitlab-subway-map',
        provider_id='gitlab',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
