# generated: '2026-06-20'
# method: generated
# source: openapi/gitlab-openapi-original.yml
overlay: 1.0.0
info:
  title: API Evangelist enhancements for GitLab API
  version: 1.0.0
extends: openapi/gitlab-openapi-original.yml
actions:
- target: $.info
  update:
    x-apievangelist-indexed: true
    x-apievangelist-provider: gitlab
    x-apievangelist-catalog: https://apis.io/gitlab
